In [16]:
import pandas as pd
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [36]:
data1 = pd.read_csv("iris_data", sep = ",", header = None)
data1.columns =  ['sep_len', 'sep_wid', 'pet_len', 'pet_wid', 'class']
data1['class'] = data1['class'].replace(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], [0, 1, 1])


data1 = data1.to_numpy()
data1

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [42]:
data2 = pd.read_csv("iris_data", sep = ",", header = None)
data2.columns =  ['sep_len', 'sep_wid', 'pet_len', 'pet_wid', 'class']
data2 = data2[data2['class'] != 'Iris-setosa']
data2['class'] = data2['class'].replace(['Iris-versicolor', 'Iris-virginica'], [0, 1])
data2 = data2.to_numpy()

data2

array([[7. , 3.2, 4.7, 1.4, 0. ],
       [6.4, 3.2, 4.5, 1.5, 0. ],
       [6.9, 3.1, 4.9, 1.5, 0. ],
       [5.5, 2.3, 4. , 1.3, 0. ],
       [6.5, 2.8, 4.6, 1.5, 0. ],
       [5.7, 2.8, 4.5, 1.3, 0. ],
       [6.3, 3.3, 4.7, 1.6, 0. ],
       [4.9, 2.4, 3.3, 1. , 0. ],
       [6.6, 2.9, 4.6, 1.3, 0. ],
       [5.2, 2.7, 3.9, 1.4, 0. ],
       [5. , 2. , 3.5, 1. , 0. ],
       [5.9, 3. , 4.2, 1.5, 0. ],
       [6. , 2.2, 4. , 1. , 0. ],
       [6.1, 2.9, 4.7, 1.4, 0. ],
       [5.6, 2.9, 3.6, 1.3, 0. ],
       [6.7, 3.1, 4.4, 1.4, 0. ],
       [5.6, 3. , 4.5, 1.5, 0. ],
       [5.8, 2.7, 4.1, 1. , 0. ],
       [6.2, 2.2, 4.5, 1.5, 0. ],
       [5.6, 2.5, 3.9, 1.1, 0. ],
       [5.9, 3.2, 4.8, 1.8, 0. ],
       [6.1, 2.8, 4. , 1.3, 0. ],
       [6.3, 2.5, 4.9, 1.5, 0. ],
       [6.1, 2.8, 4.7, 1.2, 0. ],
       [6.4, 2.9, 4.3, 1.3, 0. ],
       [6.6, 3. , 4.4, 1.4, 0. ],
       [6.8, 2.8, 4.8, 1.4, 0. ],
       [6.7, 3. , 5. , 1.7, 0. ],
       [6. , 2.9, 4.5, 1.5, 0. ],
       [5.7, 2

In [28]:
import numpy as np


In [61]:
class Perceptron:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.activation_func = self._unit_step_func
        self.weights = None
        self.bias = None
        
        
    def _unit_step_func(self, x):
        return np.where(x>= 0, 1, 0)
    
    def fit(self, X, y):
        n_samples, n_features = X.shape
        
        # init weights
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        y_ = np.array([1 if i > 0 else 0 for i in y])
        
        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_func(linear_output)
                
                update = self.lr * (y_[idx] - y_predicted)
                self.weights += update * x_i
                self.bias += update
        
    
    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.activation_func(linear_output)
        return y_predicted

In [63]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

X, y = datasets.make_blobs(n_samples=150, n_features= 2, centers = 2, cluster_std = 1.05, random_state =2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =123)


p = Perceptron(learning_rate=0.01, n_iters=1000)
p.fit(X_train, y_train)
predictions = p.predict(X_test)

print("Perceptron classification accuracy", accuracy(y_test, predictions))




Perceptron classification accuracy 1.0


In [73]:
data1_x = data1[:,0:4]
data1_y = data1[:,4]
data2_x = data2[:,0:4]
data2_y = data2[:,4]

In [81]:
X_train, X_test, y_train, y_test = train_test_split(data1_x, data1_y, test_size = 0.2, random_state =123)
p.fit(X_train, y_train)
predictions = p.predict(X_test)



array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [82]:
print(predictions)
print(y_test)

[1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 0 1 0 0 0 1 1 0]
[1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1.
 0. 0. 0. 1. 1. 0.]


In [83]:
accuracy(y_test, predictions)

1.0